### ISSUE TITLE
unable to open any feature flag from dashboard

### ISSUE THREAD

**Issue by abhijeetahuja** [launchdarkly/featureflags#3]
Gets this error on click of any feature flag on dashboard
![ld](https://cloud.githubusercontent.com/assets/10277514/24482238/94cd7dc8-153b-11e7-94ca-6b934152fc54.png)

**Comment by jkodumal** [comment]
Hey @abhijeetahuja-- apologies for that. A third-party script on our site caused navigation issues for a brief period of time today. It was reported on our status page:

http://status.launchdarkly.com/

Luckily, we feature flagged our third-party scripts, and once we isolated the issue we were able to disable the offending script.
